In [6]:
import torch 
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt


## Introduction to Tensors

In [8]:

#creating a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [ ]:
#Getting the value of a scalar
scalar.item()

7

In [12]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [18]:
#MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
matrix.ndim

2

In [20]:
matrix.shape

torch.Size([2, 2])

In [25]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [43]:
random_tensor = torch.rand(5, 5 ,5)

In [44]:
random_tensor.shape

torch.Size([5, 5, 5])

In [45]:
random_tensor

tensor([[[0.4897, 0.8242, 0.9058, 0.8106, 0.7968],
         [0.4355, 0.0148, 0.8404, 0.2445, 0.9131],
         [0.5769, 0.2588, 0.9751, 0.3639, 0.6750],
         [0.5557, 0.2569, 0.0024, 0.6203, 0.4004],
         [0.9027, 0.8965, 0.8390, 0.9435, 0.4552]],

        [[0.1318, 0.5342, 0.1847, 0.5505, 0.5885],
         [0.6691, 0.2745, 0.4461, 0.4980, 0.6257],
         [0.6376, 0.9984, 0.5778, 0.8641, 0.5197],
         [0.9434, 0.0054, 0.0700, 0.5075, 0.1520],
         [0.7488, 0.1055, 0.9822, 0.8807, 0.5178]],

        [[0.6796, 0.3407, 0.4280, 0.8602, 0.4996],
         [0.0598, 0.4911, 0.2896, 0.5901, 0.6821],
         [0.5825, 0.2537, 0.7667, 0.7304, 0.2981],
         [0.9807, 0.2733, 0.0287, 0.5756, 0.3880],
         [0.7587, 0.2639, 0.0340, 0.5828, 0.6484]],

        [[0.1596, 0.4624, 0.6567, 0.4927, 0.8562],
         [0.1272, 0.7472, 0.1152, 0.9970, 0.7259],
         [0.3132, 0.1315, 0.7464, 0.0299, 0.4032],
         [0.3197, 0.3551, 0.6315, 0.7923, 0.5915],
         [0.5237, 0.3989,

In [46]:
image_tenor = torch.rand(224, 224, 3)

In [47]:
image_tenor

tensor([[[5.5610e-01, 3.7368e-01, 9.8734e-01],
         [9.4727e-01, 2.8523e-01, 1.0603e-01],
         [5.4287e-02, 2.4393e-01, 6.8874e-01],
         ...,
         [4.2674e-01, 5.4678e-01, 6.2292e-01],
         [9.9344e-02, 2.8484e-01, 8.1910e-01],
         [2.2532e-01, 2.9907e-01, 6.2735e-02]],

        [[6.5594e-01, 4.9795e-02, 5.8367e-01],
         [8.3696e-02, 8.8939e-01, 3.7934e-01],
         [1.0371e-01, 8.7800e-01, 3.9936e-01],
         ...,
         [3.5231e-01, 2.7436e-01, 1.1588e-01],
         [4.9112e-01, 2.9968e-01, 8.6960e-01],
         [1.5403e-01, 2.5398e-01, 4.5841e-01]],

        [[7.9745e-01, 5.1091e-01, 3.3262e-02],
         [3.2693e-01, 1.1559e-01, 5.3940e-01],
         [8.8956e-01, 6.8464e-01, 3.1046e-01],
         ...,
         [8.6611e-01, 9.9502e-01, 6.4534e-01],
         [3.3171e-01, 1.0943e-01, 8.7161e-01],
         [5.6774e-01, 2.1789e-01, 1.4536e-02]],

        ...,

        [[7.3954e-01, 2.8500e-02, 5.4863e-01],
         [1.7083e-04, 6.1391e-01, 2.9552e-01]

In [48]:
image_tenor.shape

torch.Size([224, 224, 3])

In [50]:
image_tenor.ndim

3

In [59]:
#create a tensor of all zeros
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
ones_tensor.dtype

torch.float32

In [68]:
#create a range of numbers
range_tensor = torch.arange(start=0, end=1000 , step=80)
range_tensor

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [70]:
#creating tensor like
tensor_ones = torch.ones_like(input=range_tensor)
tensor_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [75]:
float_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64 , device=None)
float_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [76]:
float_tensor.dtype

torch.float64

In [77]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32 , device=None)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [78]:
int_16_tensor = torch.tensor([3, 6, 9], dtype=torch.int16 , device=None)

In [80]:
result_tensor = int_32_tensor * int_16_tensor

In [81]:
result_tensor.dtype

torch.int32

In [82]:
result_tensor.device

device(type='cpu')

## Maniplating Tensors

In [85]:
tensor1 = torch.rand(3, 4, 5)
tensor2 = torch.rand(3, 4, 5)

In [88]:
tensor1 += 10

In [89]:
tensor1

tensor([[[10.6221, 10.5044, 10.0940, 10.5722, 10.7391],
         [10.9228, 10.6668, 10.4521, 10.9039, 10.6302],
         [10.3868, 10.8666, 10.5431, 10.5482, 10.9593],
         [10.8357, 10.7215, 10.5383, 10.2402, 10.4642]],

        [[10.1630, 10.5468, 10.3133, 10.9163, 10.6023],
         [10.5243, 10.3016, 10.4094, 10.9905, 10.1387],
         [10.6303, 10.8394, 10.0402, 10.9096, 10.8588],
         [10.0576, 10.7303, 10.6137, 10.8724, 10.5796]],

        [[10.9440, 10.3646, 10.2797, 10.0870, 10.5733],
         [10.8311, 10.2697, 10.2392, 10.6396, 10.5551],
         [10.5946, 10.4984, 10.6648, 10.3260, 10.2530],
         [10.9586, 10.8623, 10.3108, 10.3636, 10.1232]]])

In [91]:
mult_tensor = torch.mul(tensor1, tensor2)
mult_tensor

tensor([[[ 3.2539,  7.2140,  7.9061,  4.8517,  5.3518],
         [ 2.4323,  5.9440,  2.9151,  4.4037,  6.3078],
         [ 4.8520,  9.1918,  0.0630,  8.3247,  4.4112],
         [ 3.4602,  6.3995,  0.2895,  6.8064,  0.4226]],

        [[ 3.0303,  9.0930,  5.2202,  8.7594,  0.6816],
         [ 4.7323,  1.4515,  6.8288,  1.4771,  9.0716],
         [ 7.9756,  3.8232,  3.9894,  4.8331, 10.4881],
         [ 6.1013,  8.2376,  2.9520,  1.3599,  2.7919]],

        [[ 3.2258,  5.7655,  3.5764,  6.0506,  6.4870],
         [ 5.4175,  5.5791,  3.8658,  9.4282,  6.1817],
         [ 8.8168,  6.2803,  9.0383,  9.6670,  1.0142],
         [ 9.5892,  2.2068,  4.3747,  0.9515,  7.6395]]])

In [94]:
## Matrix Multiplication

# Matrix multiplication in PyTorch
matrix1 = torch.tensor([[1, 2],
                         [3, 4]])
matrix2 = torch.tensor([[5, 6],
                         [7, 8]])

# Matrix multiplication using torch.mm()
matrix_mult = torch.mm(matrix1, matrix2)
matrix_mult
# Matrix multiplication using the @ operator
matrix_mult_operator = matrix1 @ matrix2

matrix_mult_operator
# Element-wise multiplication
elementwise_mult = matrix1 * matrix2
elementwise_mult


tensor([[ 5, 12],
        [21, 32]])

In [96]:
%%time

# Matrix multiplication in PyTorch
matrix1 = torch.tensor([[1, 2],
                         [3, 4]])
matrix2 = torch.tensor([[5, 6],
                         [7, 8]])

# Matrix multiplication using torch.mm()
matrix_mult = torch.mm(matrix1, matrix2)
matrix_mult

CPU times: total: 0 ns
Wall time: 261 μs


tensor([[19, 22],
        [43, 50]])

In [101]:
%%time

large_tensor1 = torch.rand(1000, 1000 ) 
large_tensor2 = torch.rand(1000, 1000)
# Matrix multiplication using torch.mm()
%prun large_matrix_mult = torch.mm(large_tensor1, large_tensor2)



 CPU times: total: 391 ms
Wall time: 435 ms


         4 function calls in 0.005 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.005    0.005    0.005    0.005 {built-in method torch.mm}
        1    0.000    0.000    0.005    0.005 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.005    0.005 {built-in method builtins.exec}

In [107]:
%%time
## Tensor Aggregation

tensor_agg = torch.tensor([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
# Find the minimum value
%time min_val = torch.min(tensor_agg)
# Find the maximum value
max_val = torch.max(tensor_agg)
# Find the mean value
mean_val = torch.mean(tensor_agg.float())
# Find the sum of all elements
sum_val = torch.sum(tensor_agg)
# Find the standard deviation
std_val = torch.std(tensor_agg.float())
# Find the variance
var_val = torch.var(tensor_agg.float())
# Print the results

#return the index of the minimum value
min_index = torch.argmin(tensor_agg)
print(f"Minimum index: {min_index}")
#return the index of the maximum value
max_index = torch.argmax(tensor_agg)
print(f"Maximum index: {max_index}")
print(f"Minimum: {min_val}")
print(f"Maximum: {max_val}")
print(f"Mean: {mean_val}")
print(f"Sum: {sum_val}")
print(f"Standard Deviation: {std_val}")
print(f"Variance: {var_val}")



CPU times: total: 0 ns
Wall time: 31 μs
Minimum index: 0
Maximum index: 8
Minimum: 1
Maximum: 9
Mean: 5.0
Sum: 45
Standard Deviation: 2.7386128902435303
Variance: 7.5
CPU times: total: 0 ns
Wall time: 10.6 ms


In [ ]:
#Reshaping - reshapes an inpt tensor to a desired shape
#view - returns a new tensor with the same data but a different shape
#stacking - combines multiple tensors along a new dimension
#squeeze - removes single-dimensional entries from the shape of a tensor
#unsqueeze - adds a single-dimensional entry to the shape of a tensor

In [108]:
x = torch.randn(1,2,1,5)
x.shape


torch.Size([1, 2, 1, 5])

In [110]:
y = torch.squeeze(x)
y.shape

torch.Size([2, 5])

In [ ]:
#torch.permute - returns a view of the original tensor with its dimensions permuted
z = torch.permute(x, (1, 0, 2, 3))
z.shape


torch.Size([2, 1, 1, 5])

In [ ]:
#image_tensor = torch.rand(224, 224, 3)
x_imng = torch.rand(224, 224, 3)
#Permute
x_imng_permuted = torch.permute(x_imng, (2, 0, 1))

## Pytorch Tensors and Numpy

In [114]:
#numpy to PyTorch tensor 
numpy_array = np.array([[1, 2, 3],
                         [4, 5, 6]])
torch_tensor = torch.from_numpy(numpy_array)

# PyTorch tensor to NumPy array
numpy_array_from_tensor = torch_tensor.numpy()
# Display the results
print("NumPy Array:\n", numpy_array)

NumPy Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#Reproducibility
# Set the random seed for reproducibility   
torch.manual_seed(42)
np.random.seed(42)
# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# Check if GPU is available
if torch.cuda.is_available():
    # Create a tensor on the GPU
    
    print(f"Tensor on GPU: {gpu_tensor}")   

Using device: cpu


In [131]:
!nvidia-smi

Tue Aug 12 07:59:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.49                 Driver Version: 566.49         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   46C    P5              6W /   75W |     925MiB /   8188MiB |     30%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [133]:
# Check for GPU
import torch
torch.cuda.is_available()

# Count number of devices
torch.cuda.device_count()

0